### ISSUE TITLE
Wraps attributes with attributes key

### ISSUE THREAD

**Issue by gching** [twilson63/html2hscript#1]
I was wondering if it is correct to wrap all the attributes of the HTML in an object and adding a key for it called 'attributes'.

For example:

``` js
<div line-width="0"></div>
```

returns

``` js
h("div", { attributes: {
    "line-width": "0"
} })
```

Looking over at the documentation over at https://github.com/dominictarr/hyperscript, attributes should just be key value pairs at the root level of the object. Specifically from the documentation:

``` js
var h = require('hyperscript')
h('a', {href: 'https://npm.im/hyperscript'}, 'hyperscript')
```

Don't know if the attributes key will effect anything but submitting this issue just in case :>

**Comment by twilson63** [comment]
corrected

h("div", { "line-width": "0"})
