### ISSUE TITLE
Pre/code: spaces and eof

### ISSUE THREAD

**Issue by SamyPesse** [twilson63/html2hscript#2]
Spaces and EOF (`\n`) are merged/removed event when in a `pre` element`.

Example:

```
parser("<pre>hello\nworld</pre>", function(err, hscript) {
})
```

gives:

```
"h("pre", [ "hello",\n"world" ])
```

which converted back to html gives: `<pre>helloworld</pre>`

**Comment by SamyPesse** [comment]
I will work on a PR to fix this.

**Comment by twilson63** [comment]
Awesome!

Thank you!

Sent from my iPhone

On Mar 18, 2015, at 8:39 AM, "Samy Pessé" notifications@github.com wrote:

I will work on a PR to fix this.
